/*
 * This file is generated by jOOQ.
 */
package org.quickstart.jooq.example.generate;


import javax.annotation.Generated;

import org.quickstart.jooq.example.generate.tables.Author;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = org.quickstart.jooq.example.generate.tables.Author.AUTHOR;
}
